services:
  postgresql:
    container_name: postgres
    image: postgres:latest
    restart: always
    networks:
      - gitdb 

    environment:
       POSTGRES_PASSWORD: 12345
       PGDATA: /var/lib/postresql/data/pgdata
    volumes:
      - opt/postgres/data: /var/lib/postgresql/data

  gitlab:
   container_name: gitlab
   image: gitlab/gitlab-ce:latest
   restart: always
   hostname: '<SERVER_DNS_NAME>'
   environment:
     GITLAB_OMNIBUS_CONFIG: |
       external_url 'https://<SERVER_DNS_NAME>'
       # Add any other gitlab.rb configuration here, each on its own line
   ports:
     - '80:80'
     - '443:443'
     - '22:22'
   networks:
     - gitdb 
   volumes:
     - /opt/gitlab/config:/etc/gitlab
     - /opt/gitlab/logs:/var/log/gitlab
     - /opt/gitlab/data:/var/opt/gitlab
   depends_on: 
     - postgres

  gitlab-runner:
   container_name: gitlab-runner
   image: gitlab/gitlab-runner:latest
   restart: always
   volumes:
     - /opt/gitlab-runner/data:/home/gitlab_ci_multi_runner/data
     - /opt/gitlab-runner/config:/etc/gitlab-runner
     - /var/run/docker.sock:/var/run/docker.sock:rw
   environment:
     - CI_SERVER_URL=https://<SERVER_DNS_NAME>/ci
   depends_on: 
     - postgres     

networks:
  gitdb: {}
       