services:
  postgre:
    container_name: postgres
    image: postgres:latest
    volumes:
      - /opt/postgres/data:/var/lib/postgresql/data
    restart: always
    networks:
      - gitdb 
    ports:
      - 5432:5432
    environment:
        POSTGRES_PASSWORD: 12345
        PGDATA: /var/lib/postresql/data/pgdata
    

  gitlab:
   container_name: gitlab
   image: gitlab/gitlab-ce:latest
   restart: never
   hostname: 127.0.0.1
   environment:
      GITLAB_SKIP_UNMIGRATED_DATA_CHECK: 'true'
      GITLAB_OMNIBUS_CONFIG: |
       external_url 'https://127.0.0.1'
       # Add any other gitlab.rb configuration here, each on its own line
   ports:
     - '80:80'
     - '443:443'
     - '22:22'
   networks:
     - gitdb 
   volumes:
     - /opt/gitlab/config:/etc/gitlab
     - /opt/gitlab/logs:/var/log/gitlab
     - /opt/gitlab/data:/var/opt/gitlab
   depends_on: 
     - postgre

  gitlab-runner:
   container_name: gitlab-runner
   image: gitlab/gitlab-runner:latest
   restart: always
   volumes:
     - /opt/gitlab-runner/data:/home/gitlab_ci_multi_runner/data
     - /opt/gitlab-runner/config:/etc/gitlab-runner
     - /var/run/docker.sock:/var/run/docker.sock:rw
   environment:
     - CI_SERVER_URL=https://127.0.0.1/ci
   depends_on: 
     - postgre     

networks:
  gitdb: {}
       