version: '3.5'
services:
  postgre:
    container_name: postgres
    image: postgres:latest
    volumes:
      - /opt/postgres/data:/var/lib/postgresql/data
    restart: always
    networks:
      - gitdb 
    ports:
      - 5432:5432
    environment:
        POSTGRES_PASSWORD: 12345
        PGDATA: /var/lib/postresql/data/pgdata
    

  gitlab:
   image: gitlab/gitlab-ce:latest
   hostname: 'localhost'
   restart: always
   container_name: gitlab-ce
   environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'http://gitlab.localhost'
      
   ports:
    - "443:443"
    - "80:80"
    - "22:22"
    
   volumes:
    - $GITLAB_HOME/config:/etc/gitlab
    - $GITLAB_HOME/data:/var/opt/gitlab
    - $GITLAB_HOME/logs:/var/log/gitlab
   networks:
    - gitlab

  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    restart: unless-stopped
    container_name: gitlab-runner
    depends_on:
      - gitlab
    volumes:
      - /data/docker/gitlab/etc/gitlab-runner:/etc/gitlab-runner
      - /data/docker/gitlab/var/run/docker.sock:/var/run/docker.sock
    networks:
      - gitlab
networks:
  gitlab:
  gitdb:
       